version: '3'
services:
  mongodb:
    image: mongo:3.6.8
    container_name: mongodb-local
    ports:
      - '27017:27017'
    volumes:
      - ./regcheq-db/database:/database
    networks:
      - 'net-regcheq'
networks:
  net-regcheq:
