version: '3'
services:
  mongodb:
    image: mongo:3.6.8
    container_name: mongodb-local
    ports:
      - '27017:27017'
    volumes:
      - ./regcheq-db/database:/database
    networks:
      - 'net-regcheq'
  api:
    build: '.'
    image: regcheq-api-image
    container_name: regcheq-api-container
    ports:
      - '8000:8000'
    networks:
      - 'net-regcheq'
networks:
  net-regcheq:
