services:
  Context.Users.application.UserGreeter:
    class: ../../../Contexts/Users/application/UserGreeter
    arguments: []

  Context.Users.infrastructure.persistence.MongoUserRepository:
    class: ../../../Contexts/Users/infrastructure/persistence/MongoUserRepository
    arguments: []

  Context.Users.application.UserGetter:
    class: ../../../Contexts/Users/application/UserGetter
    arguments: ['@Context.Users.infrastructure.persistence.MongoUserRepository']
