services:
  App.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  App.controllers.WelcomePostController:
    class: ../../controllers/WelcomePostController
    arguments: ['@Context.Users.application.UserGreeter']

  App.controllers.UserGetController:
    class: ../../controllers/UserGetController
    arguments: ['@Context.Users.application.UserGetter']
